#!/bin/bash
# 缓存优化工具使用示例脚本

echo "======================================================================"
echo "🚀 缓存优化工具使用示例"
echo "======================================================================"
echo ""

echo "【示例1】生成优化报告"
echo "----------------------------------------------------------------------"
echo "命令: python tools/auto_optimize_cache.py --report"
echo ""
echo "这将分析所有缓存，给出优化建议，包括："
echo "- 可删除的冗余缓存数量"
echo "- 可合并的连续缓存对数"
echo "- 可释放的磁盘空间"
echo ""
read -p "按回车键继续..."
echo ""

echo "【示例2】预览优化操作（推荐先预览）"
echo "----------------------------------------------------------------------"
echo "命令: python tools/auto_optimize_cache.py"
echo ""
echo "这将显示将要执行的所有操作，但不会实际执行："
echo "- [预览] 将删除: xxx.parquet (被覆盖)"
echo "- [预览] 将合并: xxx.parquet + yyy.parquet"
echo ""
read -p "按回车键继续..."
echo ""

echo "【示例3】执行优化"
echo "----------------------------------------------------------------------"
echo "命令: python tools/auto_optimize_cache.py --execute"
echo ""
echo "这将实际执行优化操作："
echo "- ✅ 删除冗余缓存"
echo "- ✅ 合并连续缓存"
echo "- ✅ 更新索引"
echo "- 🎉 显示优化结果"
echo ""
read -p "按回车键继续..."
echo ""

echo "【示例4】手动合并两个连续缓存"
echo "----------------------------------------------------------------------"
echo "命令: python tools/merge_continuous_caches.py \\"
echo "        tushare/a_stock/000001_20250101_20250630.parquet \\"
echo "        tushare/a_stock/000001_20250701_20251231.parquet"
echo ""
echo "这将合并两个指定的缓存（如果连续的话）"
echo "结果: 生成 000001_20250101_20251231.parquet"
echo ""
read -p "按回车键继续..."
echo ""

echo "【示例5】手动清理被覆盖的缓存"
echo "----------------------------------------------------------------------"
echo "命令: python tools/check_cache_overlap.py \\"
echo "        tushare/a_stock/000001_20240101_20260101.parquet \\"
echo "        tushare/a_stock/000001_20250101_20260101.parquet"
echo ""
echo "这将检查覆盖关系，删除被覆盖的小缓存"
echo "结果: 保留大缓存，删除小缓存"
echo ""
read -p "按回车键继续..."
echo ""

echo "======================================================================"
echo "📊 完整工作流示例"
echo "======================================================================"
echo ""
echo "1. 查看当前缓存状态"
echo "   python test/cache_tool.py --stats"
echo ""
echo "2. 生成优化报告"
echo "   python tools/auto_optimize_cache.py --report"
echo ""
echo "3. 预览优化操作"
echo "   python tools/auto_optimize_cache.py"
echo ""
echo "4. 执行优化"
echo "   python tools/auto_optimize_cache.py --execute"
echo ""
echo "5. 查看优化后的状态"
echo "   python test/cache_tool.py --stats"
echo ""
echo "======================================================================"
echo "🎓 更多信息"
echo "======================================================================"
echo ""
echo "快速指南: docs/缓存优化工具快速指南.md"
echo "详细文档: tools/README.md"
echo "技术实现: docs/缓存优化工具实现总结.md"
echo ""
echo "验证工具: python test/verify_tools.py"
echo ""
echo "======================================================================"
echo "✅ 示例展示完成"
echo "======================================================================"
